# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'NotificationServiceExtension' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NotificationServiceExtension

end

target 'SmartHome' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SmartHome

pod 'Masonry'

  target 'SmartHomeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SmartHomeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
