/*
 * SimpleLinkErrorID.h
 *
 *  Created on: 2017Äê11ÔÂ29ÈÕ
 *      Author: j.chen
 */

#ifndef SIMPLELINKERRORID_H_
#define SIMPLELINKERRORID_H_

enum SIMPLELINK_ERR{

	SIMPLELINK_ERR_OK			= 0,
	SIMPLELINK_ERR_UNKNOWN 		= -101,
	SIMPLELINK_ERR_SEND 		= -102,
	SIMPLELINK_ERR_MEMERY 		= -103,
	SIMPLELINK_ERR_METHOD		= -104,
	SIMPLELINK_ERR_SSID			= -105,
	SIMPLELINK_ERR_PWD			= -106,
	SIMPLELINK_ERR_IP			= -107,
	SIMPLELINK_ERR_SET			= -108,
	SIMPLELINK_ERR_RECV			= -109,
	SIMPLELINK_ERR_RUNNING		= -110,
	SIMPLELINK_ERR_SYSPWD		= -111,
	SIMPLELINK_ERR_FLAG			= -112,
	SIMPLELINK_ERR_CRYPTOKEY	= -113,
	SIMPLELINK_ERR_OPTION		= -114,
	SIMPLELINK_ERR_INIT			= -115,
	SIMPLELINK_ERR_TIMEOUT		= -116,
	SIMPLELINK_ERR_CUST			= -117,
	SIMPLELINK_ERR_NOREADY		= -118,

};



#endif /* SIMPLELINKERRORID_H_ */
